// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxlcpkhcaslcfushyuct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4bGNwa2hjYXNsY2Z1c2h5dWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTQxNzgsImV4cCI6MjA2NTQ5MDE3OH0.uS0swTU5DABu-9LX9wp4Zi1TSGCB43mc8wnb_7C_IuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);